apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: backend-argocd-server-cloudarmor
  namespace: argocd
spec:
  default:
    securityPolicy: test
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
