---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  namespace: whereami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whereami
      version: v1
  template:
    metadata:
      labels:
        app: whereami
        version: v1
    spec:
      containers:
      - name: whereami
        image: gcr.io/google-samples/whereami:v1.2.1
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: whereami
  namespace: whereami
spec:
  type: ClusterIP
  selector:
    app: whereami
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: whereami-central
  namespace: whereami
spec:
  type: ClusterIP
  selector:
    app: whereami
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: whereami-central
  namespace: whereami
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: whereami
  namespace: whereami
