configs:
  cm:
    accounts.jjk: apiKey, login
    accounts.jjk.enabled: 'true'
    exec.enabled: true

  params:
    server.insecure: true
    applicationsetcontroller.enable.progressive.syncs: true

  rbac:
    policy.csv: |
      g, jjk, role:admin

redis-ha:
  enabled: true
  
  haproxy:
    extraConfig: |
      global
        maxconn 5000

controller:
  replicas: 2
  metrics:
    enabled: true

server:
  replicas: 2
  metrics:
    enabled: true
  ingress:
    enabled: false

repoServer:
  replicas: 2
  metrics:
    enabled: true

applicationSet:
  replicas: 2
  metrics:
    enabled: true
