apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: internal-http-global-access-gateway-policy
  namespace: whereami
spec:
  default:
    allowGlobalAccess: true
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: internal-http-mc
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: internal-http-mc
  namespace: whereami
spec:
  gatewayClassName: gke-l7-gxlb-mc
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
